### ISSUE TITLE
heart icon in assets folder to be replaced

### ISSUE THREAD

**Issue by shellyannissa** [dhwanish-3/Heartless#22]
Heart icon that goes in the landing page is not exactly similar in that of the figma design. The image I have downloaded doesn't seem to have the shadow as in design.

**Comment by dhwanish-3** [comment]
Sorry for the late review
I will fix it once I download a emulator don't worry about it

**Comment by dhwanish-3** [comment]
The shadow is not supported in svg format I will change it to png
